# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickTest

  target 'QuickTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'QuickTestUITests' do
    # Pods for testing
  end

end
