# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleTest

  target 'SampleTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 0.9.0'
    pod 'Nimble', '3.0.0'
  end

  target 'SampleTestUITests' do
    # Pods for testing
  end

end
