apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: user
          envFrom:
            - configMapRef:  # kind: ConfigMap を指定する
                name: config