apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  template:
    spec:
      containers:
        - name: front-end
          image: 123456789012.dkr.ecr.ap-northeast-1.amazonaws.com/front-end
          ports:
            - containerPort: 8079