apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:  # 上書きする部分だけを書く
- path: front-end.yml
images:
  - name: 123456789012.dkr.ecr.ap-northeast-1.amazonaws.com/front-end
    newTag: "8123599"